/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Configuracoes.java
 *
 * Created on 22/10/2010, 10:33:37
 */
package utilitarios;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author wagner
 */
public class Configuracoes extends javax.swing.JFrame {

    /** Creates new form Configuracoes */
    public Configuracoes() {
        initComponents();
        set_janela("Configurações");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        caminho_Banco_de_Dados = new javax.swing.JTextField();
        Procurar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        LimpaLocal = new javax.swing.JButton();
        ConfirmaLocal = new javax.swing.JButton();
        senha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LimpaRemoto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        caminho_Banco_de_DadosRemoto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usuarioRemoto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ConfirmaRemoto = new javax.swing.JButton();
        senhaRemoto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tEnderecoProxy = new javax.swing.JTextField();
        tPortaProxy = new javax.swing.JTextField();
        ConfirmaProxy = new javax.swing.JButton();
        LimpaProxy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Caminho do Banco de Dados");

        caminho_Banco_de_Dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminho_Banco_de_DadosActionPerformed(evt);
            }
        });

        Procurar.setText("Procurar");
        Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        usuario.setText("SYSDBA");

        LimpaLocal.setText("Limpa");
        LimpaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpaLocalActionPerformed(evt);
            }
        });

        ConfirmaLocal.setText("Confirma");
        ConfirmaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaLocalActionPerformed(evt);
            }
        });

        senha.setText("masterkey");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caminho_Banco_de_Dados, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmaLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LimpaLocal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Procurar)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Procurar)
                    .addComponent(caminho_Banco_de_Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ConfirmaLocal)
                    .addComponent(LimpaLocal)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Local", jPanel1);

        LimpaRemoto.setText("Limpa");
        LimpaRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpaRemotoActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuário");

        caminho_Banco_de_DadosRemoto.setText("jdbc:firebirdsql://firebird02.kinghost.net:3050//firebird/glasswindow.gdb");
        caminho_Banco_de_DadosRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminho_Banco_de_DadosRemotoActionPerformed(evt);
            }
        });

        jLabel5.setText("Caminho do Banco de Dados");

        usuarioRemoto.setText("glasswindow");

        jLabel6.setText("Senha");

        ConfirmaRemoto.setText("Confirma");
        ConfirmaRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaRemotoActionPerformed(evt);
            }
        });

        senhaRemoto.setText("masterkey");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caminho_Banco_de_DadosRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(senhaRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmaRemoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LimpaRemoto)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(caminho_Banco_de_DadosRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usuarioRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ConfirmaRemoto)
                    .addComponent(LimpaRemoto)
                    .addComponent(senhaRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remoto", jPanel2);

        jLabel7.setText("Endereço");

        jLabel8.setText("Porta");

        ConfirmaProxy.setText("Confirma");
        ConfirmaProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaProxyActionPerformed(evt);
            }
        });

        LimpaProxy.setText("Limpa");
        LimpaProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpaProxyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tPortaProxy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(ConfirmaProxy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LimpaProxy)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tEnderecoProxy, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(302, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tEnderecoProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPortaProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(LimpaProxy)
                    .addComponent(ConfirmaProxy))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proxy", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaLocalActionPerformed
        conexao.usuario = "SYSDBA";
        try {
            // TODO add your handling code here:
            Global.conection = new conexao(caminho_Banco_de_Dados.getText().trim(), usuario.getText().trim(), senha.getText().trim());
        } catch (IOException ex) {
            Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_ConfirmaLocalActionPerformed

    private void LimpaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpaLocalActionPerformed
        // TODO add your handling code here:
        caminho_Banco_de_Dados.setText("");
        usuario.setText("");
        senha.setText("");
}//GEN-LAST:event_LimpaLocalActionPerformed

    private void ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        String caminho = null;
        String usuarioBancoDeDados = "SYSDBA";

        try {
            int res;

            res = fc.showOpenDialog(null);
            FileOutputStream file = new FileOutputStream(new File("CaminhoBanco.txt"));
            FileOutputStream fileUserBD = new FileOutputStream(new File("usuarioBancoDeDados.txt"));

            if (res == JFileChooser.APPROVE_OPTION) {
                caminho = "jdbc:firebirdsql://localhost:3050/"+fc.getSelectedFile().getAbsolutePath();
            }
            file.write(caminho.getBytes());
            fileUserBD.write(usuarioBancoDeDados.getBytes());

            caminho_Banco_de_Dados.setText(caminho);

        } catch (IOException ex) {
            Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProcurarActionPerformed

    private void LimpaRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpaRemotoActionPerformed
        caminho_Banco_de_DadosRemoto.setText("");
        usuarioRemoto.setText("");
        senhaRemoto.setText("");
    }//GEN-LAST:event_LimpaRemotoActionPerformed

    private void ConfirmaRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaRemotoActionPerformed
        // TODO add your handling code here:
        conexao.usuario = "glasswindow";

        final JFileChooser fc = new JFileChooser();
        String caminho = caminho_Banco_de_DadosRemoto.getText().trim();
        String usuarioBancoDeDados = "glasswindow";

        try {
            FileOutputStream file = new FileOutputStream(new File("CaminhoBanco.txt"));
            FileOutputStream fileUserBD = new FileOutputStream(new File("usuarioBancoDeDados.txt"));

            file.write(caminho.getBytes());
            fileUserBD.write(usuarioBancoDeDados.getBytes());

        } catch (IOException ex) {
            Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            // TODO add your handling code here:
            Global.conection = new conexao(caminho_Banco_de_DadosRemoto.getText().trim(), usuarioRemoto.getText().trim(), senhaRemoto.getText().trim());
        } catch (IOException ex) {
            Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();


    }//GEN-LAST:event_ConfirmaRemotoActionPerformed

    private void caminho_Banco_de_DadosRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminho_Banco_de_DadosRemotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caminho_Banco_de_DadosRemotoActionPerformed

    private void caminho_Banco_de_DadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminho_Banco_de_DadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caminho_Banco_de_DadosActionPerformed

    private void LimpaProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpaProxyActionPerformed
	tEnderecoProxy.setText("");
	tPortaProxy.setText("");
}//GEN-LAST:event_LimpaProxyActionPerformed

    private void ConfirmaProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaProxyActionPerformed

	System.getProperties().put("proxySet", "true");
	System.getProperties().put("http.proxyHost", tEnderecoProxy.getText().trim());
	System.getProperties().put("http.proxyPort", tPortaProxy.getText().trim());
	//System.getProperties().put("http.proxyUser", "someUserName");
	//System.getProperties().put("http.proxyPassword", "somePassword");
	JOptionPane.showMessageDialog(null, "Proxy configurado");
	
    }//GEN-LAST:event_ConfirmaProxyActionPerformed

    public void set_janela(String nome_janela) {
        setVisible(true);
        setTitle(nome_janela);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Só fecha esta janela
        setLocationRelativeTo(null);// Inicia a janela no centro da tela
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmaLocal;
    private javax.swing.JButton ConfirmaProxy;
    private javax.swing.JButton ConfirmaRemoto;
    private javax.swing.JButton LimpaLocal;
    private javax.swing.JButton LimpaProxy;
    private javax.swing.JButton LimpaRemoto;
    private javax.swing.JButton Procurar;
    private javax.swing.JTextField caminho_Banco_de_Dados;
    private javax.swing.JTextField caminho_Banco_de_DadosRemoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField senhaRemoto;
    private javax.swing.JTextField tEnderecoProxy;
    private javax.swing.JTextField tPortaProxy;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuarioRemoto;
    // End of variables declaration//GEN-END:variables
}
